##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    name = suppress-maximize
    match:class = .*
    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Clipse
windowrule {
    name = clipse-float
    match:class = ^(clipse-gui)$
    float = true
    center = true
    size = 400 600
}

# Kitty
windowrule {
    name = kitty-opacity
    match:class = ^(kitty)$
    opacity = 0.9 0.9
}

# Qalculate
windowrule {
    name = qalculate-float
    match:class = (qalculate-gtk)
    float = true
}

#####################
### WORKSPACE RULES ###
#####################

windowrule {
    name = special-floating-float
    match:workspace = name:special:floating
    float = true
}

windowrule {
    name = special-special-size
    match:workspace = name:special:special
    size = 40% 40%
}

windowrule {
    name = special-special-center
    match:workspace = name:special:special
    center = true
}

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]


###################
### LAYER RULES ###
###################

# Disable animations for hyprpicker and hyprshot (slurp selection)
layerrule {
    name = hyprpicker-noanim
    match:namespace = hyprpicker
    no_anim = on
}

layerrule {
    name = selection-noanim
    match:namespace = selection
    no_anim = on
}


##################
### XWAYLAND ###
##################

xwayland {
    force_zero_scaling = true
}